dubbo:
  scan:
    base-packages: com.jun.integ.service

  protocol:
    name: dubbo
    port: -1

  registry:
    address: nacos://47.106.179.74:8848

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 47.106.179.74:8848